spring:
  messages:
    basename: "i18n.messages,i18n.ValidationMessages"
    web:
      locale: zh_CN
  data:
    mongodb:
      uri: mongodb://root:123456@localhost:27017/ucenter?authSource=admin
logging:
  level:
    org.springframework: debug
    com.jiuhaox: debug

